var f = [];				
f[0]	= "v0.0.9";			
f[1]	= "01 Statesboro Blues.mp3";		
f[2]	= "02 Trouble No More.mp3";		
f[3]	= "03 Don't Keep Me Wonderin'.mp3";		
f[4]	= "04 Done Somebody Wrong [_].mp3";		
f[5]	= "05 In Memory of Elizabeth Reed.mp3";		
f[6]	= "06 You Don't Love Me.mp3";		
f[7]	= "07 Whipping Post [_].mp3";		
